server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thread
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/thread


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.chen.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      chen: debug
